### ISSUE TITLE
saturated heart

### ISSUE THREAD

**Issue by pettrs** [JuliusAF/imbued-heart-notifier#3]
highlight does not work with the new saturated heart. assuming all other functions also don't work with the new saturated heart
![image](https://user-images.githubusercontent.com/75093127/212470472-a8da8f36-b341-41fd-ba14-ce954f183daf.png)

**Comment by derekmu** [comment]
PR opened with changes to support saturated heart: #4

**Comment by JuliusAF** [comment]
Thanks for bringing this to my attention. 

@derekmu I've merged your PR and PRed the update into the plugin-hub. Thanks a lot for taking the time to make the PR

**Comment by JuliusAF** [comment]
Update has been merged into plugin-hub
